# Generated by Django 6.0.1 on 2026-01-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='url_img',
            field=models.URLField(null=True),
        ),
    ]
