# Generated by Django 6.0.1 on 2026-01-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_url_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='produtos/'),
        ),
    ]
