# Generated by Django 6.0.3 on 2026-03-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_pedido_itempedido_favorito"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente ⏳"),
                    ("pago", "Pago 💰"),
                    ("enviado", "Enviado 🚚"),
                    ("entregue", "Entregue ✅"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
