# Generated by Django 6.0.3 on 2026-03-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pedido_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="valor_frete",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
